Repository DataDog/orchestrion, pull requests merged in 2025-09, with the labels that each got.

#701 fix: flags only partially processed
  internal/goflags/flags.go
  internal/goflags/flags_test.go
Labels: conventional-commit/fix

#705 chore(config): Add missing function options to schema.json
  internal/injector/config/schema.json
Labels: conventional-commit/chore

#675 feat(injector): add package-filter join point with glob patterns and module filtering
  _docs/generator/doc.join.package-filter.tmpl
  internal/goenv/goenv.go
  internal/injector/aspect/join/package.go
  internal/injector/aspect/join/package_test.go
  internal/injector/config/schema.json
  internal/injector/testdata/injector/package-filter-no-match/config.yml
  internal/injector/testdata/injector/package-filter-no-match/modified.go.snap
  internal/injector/testdata/injector/package-filter-root-implements/config.yml
  internal/injector/testdata/injector/package-filter-root-implements/modified.go.snap
  internal/injector/testdata/injector/package-filter-root/config.yml
  internal/injector/testdata/injector/package-filter-root/modified.go.snap
  internal/injector/testdata/injector/package-filter-specific-module/config.yml
  internal/injector/testdata/injector/package-filter-specific-module/modified.go.snap
  internal/injector/testdata/injector/package-filter/config.yml
  internal/injector/testdata/injector/package-filter/modified.go.snap
Labels: conventional-commit/feat

#702 chore(docs): Bootstrap Architectural Decisions
  .adr-dir
  _docs/content/adr/0001-record-architecture-decisions.md
  _docs/content/adr/0002-aspect-application-order.md
Labels: conventional-commit/chore
